language: python
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-format-3.8
python:
  - "2.7"
install:
  - pushd /tmp
  - wget https://github.com/google/protobuf/releases/download/v3.5.0/protoc-3.5.0-linux-x86_64.zip
  - unzip protoc-3.5.0-linux-x86_64.zip
  - popd
  - export PATH=/tmp/bin:$PATH
script:
  - ./compile.py python
  - ./compile_single.py -d -o out2
  - clang-format-3.8 -i -style file $(find src -name "*.proto")
  - git diff --exit-code
